/* ============================================
   CRICKET MANAGEMENT PRO - MAIN JAVASCRIPT
   ============================================ */

// ============ STORAGE KEYS ============
const STORAGE_TOURNAMENTS = 'cmp_tournaments';
const STORAGE_PLAYERS = 'cmp_players';
const STORAGE_MATCHES = 'cmp_matches';
const STORAGE_MONITORING = 'cmp_storage_monitor';
const MAX_PHOTO_SIZE = 100 * 1024; // 100KB max per photo
const STORAGE_WARNING_THRESHOLD = 4.5 * 1024 * 1024; // 4.5MB warning threshold
const MAX_PHOTOS_IDBX = 50; // Max photos to keep in IndexedDB before cleanup
const STREAM_DESTINATIONS = {
  youtube: {
    label: 'YouTube Live',
    server: 'rtmps://a.rtmps.youtube.com/live2',
    help: 'Paste this server URL and your YouTube stream key into your encoder.'
  },
  facebook: {
    label: 'Facebook Live',
    server: 'rtmps://live-api-s.facebook.com:443/rtmp',
    help: 'Use this server with the stream key generated by Facebook Live Producer.'
  },
  twitch: {
    label: 'Twitch',
    server: 'rtmp://live.twitch.tv/app',
    help: 'Use your Twitch primary stream key as the stream name.'
  },
  custom: {
    label: 'Custom RTMP',
    server: '',
    help: 'Enter your own RTMP server in the stream URL field and add the stream key here.'
  }
};

// ============ GLOBAL STATE ============
let currentView = 'dashboard';
let currentTournament = null;
let currentMatch = null;
let playerPhotoData = null;
let scoreHistory = [];
let eventListeners = {};
let idbInstance = null;

// ============ INDEXEDDB WRAPPER ============
class PhotoDatabase {
  constructor() {
    this.dbName = 'CricketAppPhotos';
    this.storeName = 'photos';
    this.db = null;
  }

  async init() {
    return new Promise((resolve, reject) => {
      try {
        const request = indexedDB.open(this.dbName, 1);
        
        request.onerror = () => {
          console.error('IndexedDB init failed:', request.error);
          reject(request.error);
        };
        
        request.onsuccess = () => {
          this.db = request.result;
          resolve();
        };
        
        request.onupgradeneeded = (e) => {
          const db = e.target.result;
          if (!db.objectStoreNames.contains(this.storeName)) {
            db.createObjectStore(this.storeName, { keyPath: 'id', autoIncrement: true });
          }
        };
      } catch (err) {
        console.error('IndexedDB error:', err);
        reject(err);
      }
    });
  }

  async savePhoto(playerId, photoData) {
    return new Promise((resolve, reject) => {
      try {
        const transaction = this.db.transaction([this.storeName], 'readwrite');
        const store = transaction.objectStore(this.storeName);
        const photo = {
          playerId,
          data: photoData,
          timestamp: Date.now()
        };
        
        const request = store.add(photo);
        request.onerror = () => reject(request.error);
        request.onsuccess = () => resolve(request.result);
      } catch (err) {
        reject(err);
      }
    });
  }

  async getPhotoByPlayerId(playerId) {
    return new Promise((resolve, reject) => {
      try {
        const transaction = this.db.transaction([this.storeName], 'readonly');
        const store = transaction.objectStore(this.storeName);
        const request = store.getAll();
        
        request.onerror = () => reject(request.error);
        request.onsuccess = () => {
          const photos = request.result.filter(p => p.playerId === playerId);
          resolve(photos.length > 0 ? photos[0].data : null);
        };
      } catch (err) {
        reject(err);
      }
    });
  }

  async cleanupOldPhotos() {
    return new Promise((resolve, reject) => {
      try {
        const transaction = this.db.transaction([this.storeName], 'readwrite');
        const store = transaction.objectStore(this.storeName);
        const request = store.getAll();
        
        request.onerror = () => reject(request.error);
        request.onsuccess = () => {
          const photos = request.result.sort((a, b) => a.timestamp - b.timestamp);
          if (photos.length > MAX_PHOTOS_IDBX) {
            const toDelete = photos.slice(0, photos.length - MAX_PHOTOS_IDBX);
            toDelete.forEach(photo => {
              store.delete(photo.id);
            });
          }
          resolve();
        };
      } catch (err) {
        reject(err);
      }
    });
  }
}

// ============ STORAGE MONITORING ============
class StorageMonitor {
  static getStorageSize() {
    let size = 0;
    try {
      for (let key in localStorage) {
        if (localStorage.hasOwnProperty(key)) {
          size += localStorage[key].length + key.length;
        }
      }
    } catch (err) {
      console.error('Error calculating storage size:', err);
    }
    return size;
  }

  static getStoragePercent() {
    const size = this.getStorageSize();
    return (size / (5 * 1024 * 1024)) * 100;
  }

  static shouldWarn() {
    return this.getStorageSize() > STORAGE_WARNING_THRESHOLD;
  }

  static showWarning() {
    const size = this.getStorageSize();
    const sizeInMB = (size / (1024 * 1024)).toFixed(2);
    const percent = this.getStoragePercent().toFixed(1);
    console.warn(`Storage warning: ${sizeInMB}MB used (${percent}% of 5MB limit)`);
    
    const warningDiv = document.getElementById('storage-warning');
    if (warningDiv) {
      warningDiv.innerHTML = `
        <div style="background: rgba(255, 107, 107, 0.1); border: 1px solid #ff6b6b; padding: 12px; border-radius: 6px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center;">
          <span><strong>Storage Warning:</strong> Using ${sizeInMB}MB of 5MB limit. Old photos will be moved to archive or cleaned up.</span>
          <button onclick="StorageMonitor.cleanupPhotos()" style="background: #ff6b6b; color: white; border: none; padding: 6px 12px; border-radius: 4px; cursor: pointer;">Cleanup</button>
        </div>
      `;
      warningDiv.style.display = 'block';
    }
  }

  static async cleanupPhotos() {
    try {
      const players = loadPlayers();
      let cleaned = 0;
      
      for (const player of players) {
        if (player.photo && player.photo.length > MAX_PHOTO_SIZE) {
          if (idbInstance) {
            await idbInstance.savePhoto(player.id, player.photo);
            player.photo = null;
            cleaned++;
          }
        }
      }
      
      if (cleaned > 0) {
        savePlayers(players);
        console.log(`Cleaned up ${cleaned} photos to IndexedDB`);
      }
      
      if (idbInstance) {
        await idbInstance.cleanupOldPhotos();
      }
    } catch (err) {
      console.error('Cleanup error:', err);
    }
  }
}

// ============ INITIALIZATION ============
document.addEventListener('DOMContentLoaded', () => {
  try {
    lucide.createIcons();
    initializeApp();
  } catch (err) {
    console.error('Initialization error:', err);
  }
});

async function initializeApp() {
  try {
    // Initialize IndexedDB for photos
    try {
      idbInstance = new PhotoDatabase();
      await idbInstance.init();
    } catch (err) {
      console.warn('IndexedDB unavailable, using localStorage only:', err);
    }

    loadAllData();
    navigateTo('dashboard');
    
    // Check storage and show warning if needed
    if (StorageMonitor.shouldWarn()) {
      StorageMonitor.showWarning();
    }

    // Setup event listener cleanup
    setupEventListenerCleanup();
    updateTelecastDestination();
  } catch (err) {
    console.error('App initialization failed:', err);
  }
}

function setupEventListenerCleanup() {
  try {
    const searchInput = document.getElementById('player-search-bar');
    if (searchInput) {
      const handler = () => filterPlayersDirectory();
      searchInput.addEventListener('input', handler);
      eventListeners['playerSearch'] = { element: searchInput, handler, event: 'input' };
    }
  } catch (err) {
    console.error('Event listener setup error:', err);
  }
}

function cleanupEventListeners() {
  try {
    Object.values(eventListeners).forEach(listener => {
      if (listener.element && listener.handler) {
        listener.element.removeEventListener(listener.event, listener.handler);
      }
    });
    eventListeners = {};
  } catch (err) {
    console.error('Event listener cleanup error:', err);
  }
}

// ============ NAVIGATION ============
function navigateTo(view) {
  try {
    if (!view || typeof view !== 'string') {
      console.error('Invalid view parameter:', view);
      return;
    }

    // Hide all sections
    document.querySelectorAll('.view-section').forEach(s => s.classList.remove('active-view'));
    
    // Show selected section
    const section = document.getElementById(`view-${view}`);
    if (section) {
      section.classList.add('active-view');
    }
    
    // Update nav items
    document.querySelectorAll('.nav-item').forEach(item => item.classList.remove('active'));
    const navItem = document.getElementById(`nav-${view}`);
    if (navItem) {
      navItem.classList.add('active');
    }
    
    currentView = view;
    
    // Refresh view-specific data
    if (view === 'dashboard') {
      refreshDashboard();
    } else if (view === 'tournaments') {
      refreshTournamentsList();
    } else if (view === 'players') {
      refreshPlayersDirectory();
    } else if (view === 'history') {
      refreshMatchHistory();
    } else if (view === 'tournament-detail') {
      refreshTournamentDetail();
    }
  } catch (err) {
    console.error('Navigation error:', err);
  }
}

async function downloadMobileApp() {
  const apkPath = 'downloads/cricket-management-pro.apk';

  try {
    if (window.location.protocol === 'http:' || window.location.protocol === 'https:') {
      const response = await fetch(apkPath, { method: 'HEAD', cache: 'no-store' });
      if (!response.ok) {
        alert('The Android APK is not uploaded yet. Build the mobile app and place it at downloads/cricket-management-pro.apk, then this button will download it.');
        return;
      }
    }

    const link = document.createElement('a');
    link.href = apkPath;
    link.download = 'cricket-management-pro.apk';
    document.body.appendChild(link);
    link.click();
    link.remove();
  } catch (err) {
    console.error('Mobile app download error:', err);
    alert('The Android APK is not uploaded yet. Build the mobile app and place it at downloads/cricket-management-pro.apk.');
  }
}

// ============ MODAL MANAGEMENT ============
function openModal(modalId) {
  try {
    if (!modalId || typeof modalId !== 'string') {
      console.error('Invalid modal ID:', modalId);
      return;
    }
    
    const modal = document.getElementById(modalId);
    if (modal) {
      modal.classList.add('active');
    }
  } catch (err) {
    console.error('Modal open error:', err);
  }
}

function closeModal(modalId) {
  try {
    if (!modalId || typeof modalId !== 'string') {
      console.error('Invalid modal ID:', modalId);
      return;
    }
    
    const modal = document.getElementById(modalId);
    if (modal) {
      modal.classList.remove('active');
    }
  } catch (err) {
    console.error('Modal close error:', err);
  }
}

// ============ PHOTO UPLOAD & COMPRESSION ============
function previewPlayerPhoto() {
  try {
    const fileInput = document.getElementById('add-p-photo');
    if (!fileInput || !fileInput.files[0]) {
      console.warn('No file selected for photo upload');
      return;
    }

    const file = fileInput.files[0];

    // Validate file type
    if (!file.type.startsWith('image/')) {
      alert('Please select a valid image file');
      return;
    }

    // Validate file size (max 5MB before compression)
    if (file.size > 5 * 1024 * 1024) {
      alert('Image file is too large. Please select a smaller image.');
      return;
    }

    const reader = new FileReader();
    
    reader.onerror = () => {
      console.error('FileReader error:', reader.error);
      alert('Failed to read the image file');
    };

    reader.onload = (e) => {
      try {
        const img = new Image();
        
        img.onerror = () => {
          console.error('Image load error');
          alert('Failed to load the image');
        };

        img.onload = () => {
          try {
            // Compress image using canvas
            const canvas = document.createElement('canvas');
            const maxWidth = 200;
            const maxHeight = 200;
            let width = img.width;
            let height = img.height;
            
            if (width > height) {
              if (width > maxWidth) {
                height *= maxWidth / width;
                width = maxWidth;
              }
            } else {
              if (height > maxHeight) {
                width *= maxHeight / height;
                height = maxHeight;
              }
            }
            
            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            if (!ctx) {
              throw new Error('Failed to get canvas context');
            }

            ctx.drawImage(img, 0, 0, width, height);
            
            // Store compressed Base64
            let compressedData = canvas.toDataURL('image/jpeg', 0.8);
            
            // Further compress if exceeds max size
            let quality = 0.8;
            while (compressedData.length > MAX_PHOTO_SIZE && quality > 0.1) {
              quality -= 0.1;
              compressedData = canvas.toDataURL('image/jpeg', quality);
            }
            
            if (compressedData.length > MAX_PHOTO_SIZE) {
              alert('Image could not be compressed enough. Please use a smaller image.');
              return;
            }
            
            playerPhotoData = compressedData;
            
            // Show preview
            const preview = document.getElementById('photo-preview-box');
            if (preview) {
              preview.innerHTML = `<img src="${playerPhotoData}" alt="Player Photo">`;
            }
          } catch (err) {
            console.error('Image compression error:', err);
            alert('Failed to process the image');
          }
        };

        img.src = e.target.result;
      } catch (err) {
        console.error('Image processing error:', err);
        alert('Failed to process the image');
      }
    };

    reader.readAsDataURL(file);
  } catch (err) {
    console.error('Photo preview error:', err);
  }
}

// ============ INPUT VALIDATION ============
function validatePlayerName(name) {
  if (!name || typeof name !== 'string') return false;
  name = name.trim();
  return name.length >= 2 && name.length <= 100 && /^[a-zA-Z0-9\s\-']*$/.test(name);
}

function validateTournamentName(name) {
  if (!name || typeof name !== 'string') return false;
  name = name.trim();
  return name.length >= 2 && name.length <= 100;
}

function validateVenue(venue) {
  if (!venue || typeof venue !== 'string') return false;
  return venue.trim().length >= 2 && venue.trim().length <= 100;
}

function validateTeamName(name) {
  if (!name || typeof name !== 'string') return false;
  name = name.trim();
  return name.length >= 2 && name.length <= 100;
}

function validateOvers(overs) {
  const parsed = parseInt(overs);
  return !isNaN(parsed) && parsed > 0 && parsed <= 120;
}

// ============ PLAYER MANAGEMENT ============
function saveNewPlayer() {
  try {
    const nameInput = document.getElementById('add-p-name');
    const name = nameInput ? nameInput.value.trim() : '';
    const roleSelect = document.getElementById('add-p-role');
    const role = roleSelect ? roleSelect.value : '';
    const battingSelect = document.getElementById('add-p-batting');
    const batting = battingSelect ? battingSelect.value : '';
    const bowlingSelect = document.getElementById('add-p-bowling');
    const bowling = bowlingSelect ? bowlingSelect.value : '';
    const bioInput = document.getElementById('add-p-bio');
    const bio = bioInput ? bioInput.value.trim() : '';
    
    if (!validatePlayerName(name)) {
      alert('Player name must be 2-100 characters and contain only letters, numbers, spaces, hyphens, or apostrophes');
      return;
    }
    
    if (!role || !batting || !bowling) {
      alert('Please select all player attributes');
      return;
    }
    
    const players = loadPlayers();
    if (!Array.isArray(players)) {
      throw new Error('Invalid players data');
    }

    const newPlayer = {
      id: Date.now(),
      name,
      role,
      batting,
      bowling,
      bio,
      photo: playerPhotoData,
      team: '',
      stats: {
        matches: 0,
        runs: 0,
        balls: 0,
        fours: 0,
        sixes: 0,
        strikeRate: 0,
        wickets: 0,
        overs: 0,
        maidens: 0,
        bowlRuns: 0,
        economy: 0,
        average: 0,
        milestones: { thirties: 0, fifties: 0, seventies: 0, hundreds: 0 }
      }
    };
    
    players.push(newPlayer);
    savePlayers(players);
    
    // Reset form
    if (nameInput) nameInput.value = '';
    if (bioInput) bioInput.value = '';
    const preview = document.getElementById('photo-preview-box');
    if (preview) {
      preview.innerHTML = '<i data-lucide="camera"></i><p>Click to upload photo</p>';
    }
    playerPhotoData = null;
    
    closeModal('modal-add-player');
    lucide.createIcons();
    refreshPlayersDirectory();
    
    // Check storage
    if (StorageMonitor.shouldWarn()) {
      StorageMonitor.showWarning();
    }
  } catch (err) {
    console.error('Save player error:', err);
    alert('Failed to save player. Please try again.');
  }
}

function openAddPlayerModalGlobal() {
  try {
    playerPhotoData = null;
    const nameInput = document.getElementById('add-p-name');
    const bioInput = document.getElementById('add-p-bio');
    if (nameInput) nameInput.value = '';
    if (bioInput) bioInput.value = '';
    const preview = document.getElementById('photo-preview-box');
    if (preview) {
      preview.innerHTML = '<i data-lucide="camera"></i><p>Click to upload photo</p>';
    }
    openModal('modal-add-player');
    lucide.createIcons();
  } catch (err) {
    console.error('Open player modal error:', err);
  }
}

// ============ PLAYERS DIRECTORY ============
function refreshPlayersDirectory() {
  try {
    const players = loadPlayers();
    if (!Array.isArray(players)) {
      throw new Error('Invalid players data');
    }

    const container = document.getElementById('players-grouped-container');
    const tbody = document.getElementById('players-directory-tbody');
    
    if (!container || !tbody) {
      console.error('Missing DOM elements for players directory');
      return;
    }
    
    if (players.length === 0) {
      container.innerHTML = '<div class="empty-state"><i data-lucide="users"></i><p>No players registered yet</p></div>';
      tbody.innerHTML = '<tr><td colspan="9" class="empty-state">No players registered yet</td></tr>';
      lucide.createIcons();
      return;
    }
    
    // Group players by team
    const grouped = {};
    players.forEach(p => {
      const team = p && p.team ? p.team : 'Unassigned';
      if (!grouped[team]) grouped[team] = [];
      grouped[team].push(p);
    });
    
    // Render grouped view
    let html = '';
    Object.entries(grouped).forEach(([team, teamPlayers]) => {
      html += `
        <div class="glass-card">
          <div class="team-roster-header">
            <h3>🏏 ${team}</h3>
            <span class="player-count">${teamPlayers.length} players</span>
          </div>
          <div class="team-roster-players">
            ${teamPlayers.map(p => `
              <div class="player-card" onclick="showPlayerProfile(${p.id})">
                <div class="player-photo">
                  ${p.photo ? `<img src="${p.photo}" alt="${p.name}">` : '<i data-lucide="user"></i>'}
                </div>
                <div class="player-name">${p.name}</div>
                <div class="player-role">${p.role}</div>
                <div class="player-stats">
                  <div class="player-stat">
                    <span class="player-stat-value">${p.stats ? p.stats.matches : 0}</span>
                    <span>Matches</span>
                  </div>
                  <div class="player-stat">
                    <span class="player-stat-value">${p.stats ? p.stats.runs : 0}</span>
                    <span>Runs</span>
                  </div>
                  <div class="player-stat">
                    <span class="player-stat-value">${p.stats ? p.stats.wickets : 0}</span>
                    <span>Wkts</span>
                  </div>
                </div>
              </div>
            `).join('')}
          </div>
        </div>
      `;
    });
    
    container.innerHTML = html;
    
    // Also populate table view
    tbody.innerHTML = players.map(p => `
      <tr onclick="showPlayerProfile(${p.id})">
        <td>
          <div style="width: 32px; height: 32px; border-radius: 50%; background: linear-gradient(135deg, #6c5dd3, #ff6b6b); display: flex; align-items: center; justify-content: center; overflow: hidden;">
            ${p.photo ? `<img src="${p.photo}" style="width: 100%; height: 100%; object-fit: cover;">` : '<i data-lucide="user" style="width: 16px; height: 16px;"></i>'}
          </div>
        </td>
        <td>${p.name}</td>
        <td>${p.team || '-'}</td>
        <td>${p.role}</td>
        <td>${p.stats ? p.stats.matches : 0}</td>
        <td>${p.stats ? p.stats.runs : 0}</td>
        <td>${p.stats ? p.stats.wickets : 0}</td>
        <td>${p.stats && p.stats.matches > 0 ? (p.stats.runs / p.stats.matches).toFixed(1) : '0.0'}</td>
        <td>${p.stats ? p.stats.economy.toFixed(2) : '0.00'}</td>
      </tr>
    `).join('');
    
    lucide.createIcons();
  } catch (err) {
    console.error('Refresh players directory error:', err);
  }
}

function filterPlayersDirectory() {
  try {
    const searchInput = document.getElementById('player-search-bar');
    const searchTerm = searchInput ? searchInput.value.toLowerCase() : '';
    const players = loadPlayers();
    
    if (!Array.isArray(players)) {
      throw new Error('Invalid players data');
    }

    const filtered = players.filter(p => 
      p && (
        (p.name && p.name.toLowerCase().includes(searchTerm)) || 
        (p.team && p.team.toLowerCase().includes(searchTerm))
      )
    );
    
    // Update display with filtered results
    const tbody = document.getElementById('players-directory-tbody');
    if (!tbody) return;

    tbody.innerHTML = filtered.map(p => `
      <tr onclick="showPlayerProfile(${p.id})">
        <td>
          <div style="width: 32px; height: 32px; border-radius: 50%; background: linear-gradient(135deg, #6c5dd3, #ff6b6b); display: flex; align-items: center; justify-content: center; overflow: hidden;">
            ${p.photo ? `<img src="${p.photo}" style="width: 100%; height: 100%; object-fit: cover;">` : '<i data-lucide="user" style="width: 16px; height: 16px;"></i>'}
          </div>
        </td>
        <td>${p.name}</td>
        <td>${p.team || '-'}</td>
        <td>${p.role}</td>
        <td>${p.stats ? p.stats.matches : 0}</td>
        <td>${p.stats ? p.stats.runs : 0}</td>
        <td>${p.stats ? p.stats.wickets : 0}</td>
        <td>${p.stats && p.stats.matches > 0 ? (p.stats.runs / p.stats.matches).toFixed(1) : '0.0'}</td>
        <td>${p.stats ? p.stats.economy.toFixed(2) : '0.00'}</td>
      </tr>
    `).join('');
  } catch (err) {
    console.error('Filter players error:', err);
  }
}

function showPlayerProfile(playerId) {
  try {
    if (!playerId || typeof playerId !== 'number') {
      console.error('Invalid player ID:', playerId);
      return;
    }

    const players = loadPlayers();
    if (!Array.isArray(players)) {
      throw new Error('Invalid players data');
    }

    const player = players.find(p => p && p.id === playerId);
    if (!player) {
      console.warn('Player not found:', playerId);
      return;
    }
    
    // Populate modal with safe defaults
    const nameEl = document.getElementById('prof-modal-name');
    const teamEl = document.getElementById('prof-modal-team');
    const roleEl = document.getElementById('prof-modal-role');
    const styleEl = document.getElementById('prof-modal-style');
    const bioEl = document.getElementById('prof-modal-bio');
    const avatarEl = document.getElementById('prof-modal-avatar');

    if (nameEl) nameEl.textContent = player.name || 'Unknown';
    if (teamEl) teamEl.textContent = player.team || 'Unassigned';
    if (roleEl) roleEl.textContent = player.role || '-';
    if (styleEl) styleEl.textContent = `${player.batting || '-'} / ${player.bowling || '-'}`;
    if (bioEl) bioEl.textContent = player.bio || 'No bio available';
    
    // Avatar
    if (avatarEl) {
      if (player.photo) {
        avatarEl.innerHTML = `<img src="${player.photo}" style="width: 100%; height: 100%; object-fit: cover;">`;
      } else {
        avatarEl.innerHTML = '<i data-lucide="user" style="width: 48px; height: 48px;"></i>';
      }
    }
    
    // Stats with safe access
    const stats = player.stats || {};
    const matEl = document.getElementById('prof-modal-bat-mat');
    const runsEl = document.getElementById('prof-modal-bat-runs');
    const avgSrEl = document.getElementById('prof-modal-bat-avg-sr');

    if (matEl) matEl.textContent = stats.matches || 0;
    if (runsEl) runsEl.textContent = stats.runs || 0;
    
    const batAvg = stats.matches && stats.matches > 0 ? (stats.runs / stats.matches).toFixed(1) : '0.0';
    const sr = stats.balls && stats.balls > 0 ? ((stats.runs / stats.balls) * 100).toFixed(0) : '0';
    if (avgSrEl) avgSrEl.textContent = `${batAvg} / ${sr}`;
    
    // Milestones
    const milestones = stats.milestones || {};
    let milestonesHtml = '';
    if (milestones.thirties > 0) milestonesHtml += `<span class="cap-badge cap-orange">30+ (${milestones.thirties})</span>`;
    if (milestones.fifties > 0) milestonesHtml += `<span class="cap-badge cap-orange">50+ (${milestones.fifties})</span>`;
    if (milestones.seventies > 0) milestonesHtml += `<span class="cap-badge cap-orange">70+ (${milestones.seventies})</span>`;
    if (milestones.hundreds > 0) milestonesHtml += `<span class="cap-badge cap-orange">100+ (${milestones.hundreds})</span>`;
    const milestonesEl = document.getElementById('prof-modal-milestones-row');
    if (milestonesEl) {
      milestonesEl.innerHTML = milestonesHtml || '<span style="color: var(--text-muted);">No milestones yet</span>';
    }
    
    // Bowling
    const wktEl = document.getElementById('prof-modal-bowl-wkts');
    const econAvgEl = document.getElementById('prof-modal-bowl-econ-avg');
    const oversEl = document.getElementById('prof-modal-bowl-overs');

    if (wktEl) wktEl.textContent = stats.wickets || 0;
    if (econAvgEl) econAvgEl.textContent = `${(stats.economy || 0).toFixed(2)} / ${(stats.average || 0).toFixed(1)}`;
    if (oversEl) oversEl.textContent = (stats.overs || 0).toFixed(1);
    
    openModal('modal-player-profile');
    lucide.createIcons();
  } catch (err) {
    console.error('Show player profile error:', err);
  }
}

// ============ LIVE STREAM HANDLERS ============
function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function isAllowedStreamUrl(url) {
  try {
    const parsed = new URL(url);
    return ['http:', 'https:', 'rtmp:', 'rtmps:'].includes(parsed.protocol);
  } catch (err) {
    return false;
  }
}

function getVideoScoreOverlayHtml() {
  const team = document.getElementById('score-live-team-label')?.textContent || 'Scorecard Ready';
  const score = document.getElementById('score-live-total')?.textContent || '0/0';
  const overs = document.getElementById('score-live-overs')?.textContent || '0.0 Overs';

  return `
    <div class="video-score-overlay" id="video-score-overlay">
      <span id="video-overlay-team">${escapeHtml(team)}</span>
      <strong id="video-overlay-score">${escapeHtml(score)}</strong>
      <span id="video-overlay-overs">${escapeHtml(overs)}</span>
    </div>
  `;
}

function renderStreamFrame(contentHtml) {
  const videoContainer = document.getElementById('live-stream-video');
  if (!videoContainer) return;
  videoContainer.innerHTML = `${contentHtml}${getVideoScoreOverlayHtml()}`;
  lucide.createIcons();
}

function updateLiveStreamOverlay() {
  const team = document.getElementById('score-live-team-label')?.textContent || 'Scorecard Ready';
  const score = document.getElementById('score-live-total')?.textContent || '0/0';
  const overs = document.getElementById('score-live-overs')?.textContent || '0.0 Overs';

  const teamEl = document.getElementById('video-overlay-team');
  const scoreEl = document.getElementById('video-overlay-score');
  const oversEl = document.getElementById('video-overlay-overs');

  if (teamEl) teamEl.textContent = team;
  if (scoreEl) scoreEl.textContent = score;
  if (oversEl) oversEl.textContent = overs;
}

function loadStreamURL() {
  try {
    const urlInput = document.getElementById('stream-url-input');
    const url = urlInput ? urlInput.value.trim() : '';
    
    if (!url) {
      alert('Please enter a stream URL');
      return;
    }
    
    if (!isAllowedStreamUrl(url)) {
      alert('Please enter a valid http, https, rtmp, or rtmps stream URL');
      return;
    }
    
    // Check if it's a YouTube URL
    if (url.includes('youtube.com') || url.includes('youtu.be')) {
      const videoId = extractYouTubeId(url);
      if (!videoId) {
        alert('Invalid YouTube URL');
        return;
      }
      renderStreamFrame(`
        <iframe 
          src="https://www.youtube.com/embed/${videoId}?autoplay=1" 
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
          allowfullscreen>
        </iframe>
      `);
    } else if (url.startsWith('rtmp://') || url.startsWith('rtmps://')) {
      renderStreamFrame(`
        <div class="broadcast-placeholder">
          <i data-lucide="radio-tower" style="width: 48px; height: 48px; opacity: 0.5;"></i>
          <p>RTMP telecast destination ready</p>
          <div class="live-indicator">
            <span class="live-dot"></span>
            <span>ENCODER</span>
          </div>
          <div style="margin-top: 16px; font-size: 12px; color: var(--text-secondary); max-width: 90%;">
            Browsers cannot play RTMP directly. Use the telecast details below in OBS, Larix Broadcaster, Streamlabs, or another encoder.
          </div>
        </div>
      `);
    } else {
      renderStreamFrame(`
        <video controls style="background: #000;">
          <source src="${escapeHtml(url)}">
          Your browser does not support the video tag.
        </video>
      `);
    }
  } catch (err) {
    console.error('Load stream URL error:', err);
    alert('Failed to load stream');
  }
}

function extractYouTubeId(url) {
  try {
    const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
    const match = url.match(regExp);
    return (match && match[2].length === 11) ? match[2] : '';
  } catch (err) {
    console.error('Extract YouTube ID error:', err);
    return '';
  }
}

function toggleSimulatedBroadcast() {
  try {
    renderStreamFrame(`
      <div class="broadcast-placeholder">
        <i data-lucide="video" style="width: 48px; height: 48px; opacity: 0.5;"></i>
        <p>Simulated Broadcast Feed</p>
        <div class="live-indicator">
          <span class="live-dot"></span>
          <span>LIVE</span>
        </div>
        <div style="margin-top: 16px; font-size: 12px; color: var(--text-secondary);">
          <p>Score: 45/2 (6.3 overs)</p>
          <p>Bowler Speed: 138 km/h</p>
        </div>
      </div>
    `);
  } catch (err) {
    console.error('Toggle simulated broadcast error:', err);
  }
}

function updateTelecastDestination() {
  try {
    const platformKey = document.getElementById('telecast-platform-select')?.value || 'youtube';
    const destination = STREAM_DESTINATIONS[platformKey] || STREAM_DESTINATIONS.youtube;
    const streamUrlInput = document.getElementById('stream-url-input');
    const customServer = streamUrlInput ? streamUrlInput.value.trim() : '';
    const server = platformKey === 'custom' ? customServer : destination.server;
    const output = document.getElementById('telecast-destination');

    if (output) {
      output.innerHTML = `
        <strong>${escapeHtml(destination.label)}:</strong>
        Server URL: ${escapeHtml(server || 'Enter a custom RTMP server above')}<br>
        ${escapeHtml(destination.help)}
      `;
    }
  } catch (err) {
    console.error('Update telecast destination error:', err);
  }
}

async function copyTelecastInfo() {
  try {
    updateTelecastDestination();
    const platformKey = document.getElementById('telecast-platform-select')?.value || 'youtube';
    const destination = STREAM_DESTINATIONS[platformKey] || STREAM_DESTINATIONS.youtube;
    const streamKey = document.getElementById('telecast-stream-key')?.value.trim() || '[paste stream key here]';
    const customServer = document.getElementById('stream-url-input')?.value.trim() || '';
    const server = platformKey === 'custom' ? customServer : destination.server;
    const score = document.getElementById('score-live-total')?.textContent || '0/0';
    const overs = document.getElementById('score-live-overs')?.textContent || '0.0 Overs';
    const text = [
      `Platform: ${destination.label}`,
      `Server URL: ${server || '[enter RTMP server]'}`,
      `Stream Key: ${streamKey}`,
      `Score overlay: ${score} (${overs})`
    ].join('\n');

    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      alert('Telecast info copied');
    } else {
      window.prompt('Copy telecast info:', text);
    }
  } catch (err) {
    console.error('Copy telecast info error:', err);
    alert('Unable to copy telecast info');
  }
}

// ============ CREASE DETAILS FIX ============
function updateCreaseDetails() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  const tbody = document.getElementById('score-crease-tbody');
  
  if (!inn.batsmen || inn.batsmen.length < 2) return;
  
  const striker = inn.batsmen[inn.strikerIdx];
  const nonStriker = inn.batsmen[inn.nonStrikerIdx];
  
  const strikerSR = striker.balls > 0 ? ((striker.runs / striker.balls) * 100).toFixed(0) : 0;
  const nonStrikerSR = nonStriker.balls > 0 ? ((nonStriker.runs / nonStriker.balls) * 100).toFixed(0) : 0;
  
  tbody.innerHTML = `
    <tr style="background: rgba(108, 93, 211, 0.1);">
      <td><strong>${striker.name}</strong> (Striker)</td>
      <td>${striker.runs}</td>
      <td>${striker.balls}</td>
      <td>${striker.fours}</td>
      <td>${striker.sixes}</td>
      <td>${strikerSR}</td>
    </tr>
    <tr>
      <td>${nonStriker.name}</td>
      <td>${nonStriker.runs}</td>
      <td>${nonStriker.balls}</td>
      <td>${nonStriker.fours}</td>
      <td>${nonStriker.sixes}</td>
      <td>${nonStrikerSR}</td>
    </tr>
  `;
}

function changeCreaseStriker() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const strikerSelect = document.getElementById('score-striker-select');
  const newStrikerName = strikerSelect.value;
  const inn = currentMatch.currentInning;
  
  const newStrikerIdx = inn.batsmen.findIndex(b => b.name === newStrikerName);
  if (newStrikerIdx !== -1) {
    inn.strikerIdx = newStrikerIdx;
    inn.nonStrikerIdx = inn.batsmen.findIndex((b, i) => i !== newStrikerIdx);
    updateCreaseDetails();
  }
}

// ============ SCORING FUNCTIONS ============
function scoreBall(runs) {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  const striker = inn.batsmen[inn.strikerIdx];
  
  // Add to score history for undo
  scoreHistory.push(JSON.parse(JSON.stringify(inn)));
  
  striker.runs += runs;
  striker.balls++;
  
  if (runs === 4) striker.fours++;
  if (runs === 6) striker.sixes++;
  
  inn.totalRuns += runs;
  inn.legalBalls++;
  
  // Add to current over
  if (!inn.currentOver) inn.currentOver = [];
  inn.currentOver.push(runs);
  
  // Swap ends if odd runs
  if (runs % 2 === 1) {
    [inn.strikerIdx, inn.nonStrikerIdx] = [inn.nonStrikerIdx, inn.strikerIdx];
  }
  
  // Check if over is complete
  if (inn.legalBalls % 6 === 0) {
    inn.completedOvers.push([...inn.currentOver]);
    inn.currentOver = [];
    [inn.strikerIdx, inn.nonStrikerIdx] = [inn.nonStrikerIdx, inn.strikerIdx];
  }
  
  updateCreaseDetails();
  updateLiveScore();
  updateCurrentOverDisplay();
  saveCurrentMatch();
}

function scoreExtra(type) {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  // Map type names to their HTML element IDs
  const idMap = { 'Wide': 'score-wide-runs', 'NoBall': 'score-noball-runs', 'Bye': 'score-byes-runs', 'LegBye': 'score-legbyes-runs' };
  const runsSelect = document.getElementById(idMap[type] || `score-${type.toLowerCase()}-runs`);
  const runs = parseInt(runsSelect.value) || 1;
  
  // Add to score history
  scoreHistory.push(JSON.parse(JSON.stringify(inn)));
  
  inn.totalRuns += runs;
  
  // Extras don't count as legal balls
  if (!inn.extras) inn.extras = {};
  inn.extras[type] = (inn.extras[type] || 0) + runs;
  
  // Add to current over (but not as legal ball)
  if (!inn.currentOver) inn.currentOver = [];
  inn.currentOver.push(`${type}(${runs})`);
  
  updateLiveScore();
  updateCurrentOverDisplay();
  saveCurrentMatch();
}

function updateLiveScore() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  document.getElementById('score-live-total').textContent = `${inn.totalRuns}/${inn.totalWkts}`;
  
  const overs = Math.floor(inn.legalBalls / 6);
  const balls = inn.legalBalls % 6;
  document.getElementById('score-live-overs').textContent = `${overs}.${balls} Overs`;
  
  const rr = inn.legalBalls > 0 ? (inn.totalRuns / (inn.legalBalls / 6)).toFixed(2) : '0.00';
  document.getElementById('score-live-rr').textContent = rr;
  updateLiveStreamOverlay();
}

function updateCurrentOverDisplay() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  const ballsRow = document.getElementById('score-current-over-balls');
  
  if (!inn.currentOver || inn.currentOver.length === 0) {
    ballsRow.innerHTML = '<span style="font-size: 13px; color: var(--text-muted)">Waiting for first ball...</span>';
    return;
  }
  
  const ballsHtml = inn.currentOver.map((ball, idx) => {
    const isExtra = typeof ball === 'string';
    const ballValue = isExtra ? ball : ball;
    return `<span style="display: inline-block; width: 32px; height: 32px; border-radius: 50%; background: ${isExtra ? 'rgba(255,107,107,0.2)' : 'rgba(108,93,211,0.2)'}; display: flex; align-items: center; justify-content: center; font-weight: 700; font-size: 12px;">${ballValue}</span>`;
  }).join('');
  
  ballsRow.innerHTML = ballsHtml;
}

function undoScoreAction() {
  if (scoreHistory.length === 0) {
    alert('No actions to undo');
    return;
  }
  
  currentMatch.currentInning = scoreHistory.pop();
  updateCreaseDetails();
  updateLiveScore();
  updateCurrentOverDisplay();
  saveCurrentMatch();
}

function confirmEndInnings() {
  if (!currentMatch) return;
  
  if (confirm('Are you sure you want to end this innings?')) {
    currentMatch.currentInning.isComplete = true;
    saveCurrentMatch();
    alert('Innings ended. Ready for next innings.');
  }
}

function triggerWicketModal() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  const batsmen = inn.batsmen.filter(b => !b.dismissed);
  
  const select = document.getElementById('wkt-batsman-out-select');
  select.innerHTML = batsmen.map(b => `<option value="${b.name}">${b.name}</option>`).join('');
  
  openModal('modal-wicket-details');
}

function saveWicketAction() {
  if (!currentMatch || !currentMatch.currentInning) return;
  
  const inn = currentMatch.currentInning;
  const batsmanName = document.getElementById('wkt-batsman-out-select').value;
  const dismissalType = document.getElementById('wkt-dismissal-type-select').value;
  
  const batsman = inn.batsmen.find(b => b.name === batsmanName);
  if (!batsman) return;

  scoreHistory.push(JSON.parse(JSON.stringify(inn)));
  const dismissedIndex = inn.batsmen.indexOf(batsman);
  
  batsman.dismissed = true;
  batsman.dismissal = dismissalType;
  inn.totalWkts++;
  
  const replacementIndex = inn.batsmen.findIndex((b, index) =>
    !b.dismissed && index !== inn.strikerIdx && index !== inn.nonStrikerIdx
  );

  if (replacementIndex !== -1) {
    if (dismissedIndex === inn.strikerIdx) {
      inn.strikerIdx = replacementIndex;
    } else if (dismissedIndex === inn.nonStrikerIdx) {
      inn.nonStrikerIdx = replacementIndex;
    }
  }
  
  updateCreaseDetails();
  updateLiveScore();
  saveCurrentMatch();
  closeModal('modal-wicket-details');
}

// ============ TOURNAMENT MANAGEMENT ============
function saveNewTournament() {
  try {
    const nameInput = document.getElementById('add-t-name');
    const venueInput = document.getElementById('add-t-venue');
    const oversSelect = document.getElementById('add-t-overs');

    const name = nameInput ? nameInput.value.trim() : '';
    const venue = venueInput ? venueInput.value.trim() : '';
    const overs = oversSelect ? oversSelect.value : '';
    
    if (!validateTournamentName(name)) {
      alert('Tournament name must be 2-100 characters');
      return;
    }

    if (!validateVenue(venue)) {
      alert('Venue must be 2-100 characters');
      return;
    }

    if (!validateOvers(overs)) {
      alert('Please select valid overs');
      return;
    }
    
    const tournaments = loadTournaments();
    if (!Array.isArray(tournaments)) {
      throw new Error('Invalid tournaments data');
    }

    const newTournament = {
      id: Date.now(),
      name,
      venue,
      overs: parseInt(overs),
      teams: [],
      matches: [],
      standings: []
    };
    
    tournaments.push(newTournament);
    saveTournaments(tournaments);
    
    if (nameInput) nameInput.value = '';
    if (venueInput) venueInput.value = '';
    closeModal('modal-add-tournament');
    refreshTournamentsList();
  } catch (err) {
    console.error('Save tournament error:', err);
    alert('Failed to save tournament. Please try again.');
  }
}

function saveNewTeam() {
  try {
    if (!currentTournament) {
      alert('Please select a tournament first');
      return;
    }
    
    const teamInput = document.getElementById('add-team-name');
    const teamName = teamInput ? teamInput.value.trim() : '';
    
    if (!validateTeamName(teamName)) {
      alert('Team name must be 2-100 characters');
      return;
    }
    
    if (!currentTournament.teams) {
      currentTournament.teams = [];
    }

    currentTournament.teams.push({
      id: Date.now(),
      name: teamName,
      players: [],
      matches: 0,
      wins: 0,
      losses: 0,
      points: 0
    });
    
    const tournaments = loadTournaments();
    if (!Array.isArray(tournaments)) {
      throw new Error('Invalid tournaments data');
    }

    const idx = tournaments.findIndex(t => t && t.id === currentTournament.id);
    if (idx !== -1) {
      tournaments[idx] = currentTournament;
      saveTournaments(tournaments);
    }
    
    if (teamInput) teamInput.value = '';
    closeModal('modal-add-team');
    refreshTournamentDetail();
  } catch (err) {
    console.error('Save team error:', err);
    alert('Failed to save team. Please try again.');
  }
}

function saveScheduledMatch() {
  try {
    if (!currentTournament) {
      alert('Please select a tournament first');
      return;
    }
    
    const teamASelect = document.getElementById('schedule-teamA-select');
    const teamBSelect = document.getElementById('schedule-teamB-select');

    const teamA = teamASelect ? teamASelect.value : '';
    const teamB = teamBSelect ? teamBSelect.value : '';
    
    if (!teamA || !teamB) {
      alert('Please select both teams');
      return;
    }

    if (teamA === teamB) {
      alert('Please select two different teams');
      return;
    }
    
    if (!currentTournament.matches) {
      currentTournament.matches = [];
    }

    currentTournament.matches.push({
      id: Date.now(),
      teamA,
      teamB,
      status: 'scheduled',
      date: new Date().toLocaleDateString()
    });
    
    const tournaments = loadTournaments();
    if (!Array.isArray(tournaments)) {
      throw new Error('Invalid tournaments data');
    }

    const idx = tournaments.findIndex(t => t && t.id === currentTournament.id);
    if (idx !== -1) {
      tournaments[idx] = currentTournament;
      saveTournaments(tournaments);
    }
    
    closeModal('modal-schedule-match');
    refreshTournamentDetail();
  } catch (err) {
    console.error('Save scheduled match error:', err);
    alert('Failed to schedule match. Please try again.');
  }
}

function refreshTournamentDetail() {
  try {
    if (!currentTournament) return;
    
    const nameEl = document.getElementById('tdetail-name');
    const metaEl = document.getElementById('tdetail-meta');
    const standingsEl = document.getElementById('tdetail-standings-tbody');
    const teamsEl = document.getElementById('tdetail-teams-ul');

    if (nameEl) nameEl.textContent = currentTournament.name || 'Unknown';
    if (metaEl) metaEl.textContent = `${currentTournament.venue || '-'} • ${currentTournament.overs || '-'} Overs`;
    
    // Populate standings
    if (standingsEl) {
      standingsEl.innerHTML = (currentTournament.teams || []).map((team, idx) => `
        <tr>
          <td>${idx + 1}</td>
          <td>${team.name}</td>
          <td>${team.matches}</td>
          <td>${team.wins}</td>
          <td>${team.losses}</td>
          <td>0</td>
          <td>0</td>
          <td>0.00</td>
          <td>${team.points}</td>
        </tr>
      `).join('');
    }
    
    // Populate teams list
    if (teamsEl) {
      teamsEl.innerHTML = (currentTournament.teams || []).map(team => `
        <li class="nav-item" onclick="selectTeamRoster('${team.name}')">
          <a>${team.name}</a>
        </li>
      `).join('');
    }
  } catch (err) {
    console.error('Refresh tournament detail error:', err);
  }
}

function selectTeamRoster(teamName) {
  try {
    if (!currentTournament || typeof teamName !== 'string') return;
    
    const team = currentTournament.teams && currentTournament.teams.find(t => t && t.name === teamName);
    if (!team) return;
    
    const titleEl = document.getElementById('tdetail-team-roster-title');
    if (titleEl) titleEl.textContent = `${teamName} Roster`;
    
    const tbody = document.getElementById('tdetail-roster-tbody');
    if (!tbody) return;

    if (!team.players || team.players.length === 0) {
      tbody.innerHTML = '<tr><td colspan="4" class="empty-state">No players in this team yet</td></tr>';
      return;
    }
    
    const players = loadPlayers();
    if (!Array.isArray(players)) {
      throw new Error('Invalid players data');
    }

    tbody.innerHTML = (team.players || []).map(playerId => {
      const player = players.find(p => p && p.id === playerId);
      if (!player) return '';
      return `
        <tr>
          <td>${player.name}</td>
          <td>${player.role}</td>
          <td>${player.batting}</td>
          <td>${player.bowling}</td>
        </tr>
      `;
    }).join('');
  } catch (err) {
    console.error('Select team roster error:', err);
  }
}

// ============ DASHBOARD ============
function refreshDashboard() {
  try {
    const tournaments = loadTournaments();
    const players = loadPlayers();
    const matches = loadMatches();
    
    const tourneysEl = document.getElementById('dash-tourneys-count');
    const playersEl = document.getElementById('dash-players-count');
    const matchesEl = document.getElementById('dash-matches-count');

    if (tourneysEl) tourneysEl.textContent = Array.isArray(tournaments) ? tournaments.length : 0;
    if (playersEl) playersEl.textContent = Array.isArray(players) ? players.length : 0;
    if (matchesEl) matchesEl.textContent = Array.isArray(matches) ? matches.length : 0;
  } catch (err) {
    console.error('Refresh dashboard error:', err);
  }
}

// ============ TOURNAMENTS ============
function refreshTournamentsList() {
  try {
    const tournaments = loadTournaments();
    const container = document.getElementById('tournaments-list');
    
    if (!container) {
      console.error('Tournaments list container not found');
      return;
    }

    if (!Array.isArray(tournaments) || tournaments.length === 0) {
      container.innerHTML = '<div class="empty-state"><i data-lucide="award"></i><p>No tournaments created yet</p></div>';
      lucide.createIcons();
      return;
    }
    
    container.innerHTML = tournaments.map(t => {
      if (!t) return '';
      return `
        <div class="glass-card" onclick="viewTournamentDetail(${t.id})">
          <h3 style="font-size: 16px; font-weight: 700; margin-bottom: 8px;">${t.name || 'Unknown'}</h3>
          <p style="font-size: 12px; color: var(--text-secondary); margin-bottom: 12px;">${t.venue || '-'}</p>
          <div style="display: flex; justify-content: space-between; font-size: 12px;">
            <span>Teams: ${t.teams ? t.teams.length : 0}</span>
            <span>Overs: ${t.overs || '-'}</span>
          </div>
        </div>
      `;
    }).join('');
    
    lucide.createIcons();
  } catch (err) {
    console.error('Refresh tournaments list error:', err);
  }
}

function viewTournamentDetail(tourneyId) {
  try {
    if (!tourneyId || typeof tourneyId !== 'number') {
      console.error('Invalid tournament ID:', tourneyId);
      return;
    }

    const tournaments = loadTournaments();
    currentTournament = tournaments && tournaments.find(t => t && t.id === tourneyId);
    if (currentTournament) {
      navigateTo('tournament-detail');
    }
  } catch (err) {
    console.error('View tournament detail error:', err);
  }
}

// ============ MATCH HISTORY ============
function refreshMatchHistory() {
  try {
    const matches = loadMatches();
    const container = document.getElementById('history-match-list');
    
    if (!container) {
      console.error('Match history container not found');
      return;
    }

    if (!Array.isArray(matches) || matches.length === 0) {
      container.innerHTML = '<div class="empty-state"><i data-lucide="history"></i><p>No matches recorded yet</p></div>';
      lucide.createIcons();
      return;
    }
    
    container.innerHTML = matches.map(m => {
      if (!m) return '';
      return `
        <div class="glass-card" onclick="viewMatchDetail(${m.id})">
          <h3 style="font-size: 16px; font-weight: 700; margin-bottom: 8px;">${m.teamA || '-'} vs ${m.teamB || '-'}</h3>
          <p style="font-size: 12px; color: var(--text-secondary); margin-bottom: 12px;">${m.date || '-'}</p>
          <div style="font-size: 13px; font-weight: 600; color: var(--accent);">${m.result || 'No result'}</div>
        </div>
      `;
    }).join('');
    
    lucide.createIcons();
  } catch (err) {
    console.error('Refresh match history error:', err);
  }
}

function viewMatchDetail(matchId) {
  try {
    if (!matchId || typeof matchId !== 'number') {
      console.error('Invalid match ID:', matchId);
      return;
    }

    const matches = loadMatches();
    currentMatch = matches && matches.find(m => m && m.id === matchId);
    if (currentMatch) {
      navigateTo('match-center');
    }
  } catch (err) {
    console.error('View match detail error:', err);
  }
}

// ============ LIVE SCORER SETUP ============
function toggleSetupMatchSelects() {
  try {
    const typeSelect = document.getElementById('score-match-type');
    const type = typeSelect ? typeSelect.value : '';
    const fields = document.getElementById('setup-tournament-fields');
    if (fields) {
      fields.style.display = type === 'tournament' ? 'block' : 'none';
    }
  } catch (err) {
    console.error('Toggle setup match selects error:', err);
  }
}

function addScorerPlayerInput(team) {
  try {
    if (!team || typeof team !== 'string') {
      console.error('Invalid team parameter:', team);
      return;
    }

    const container = document.getElementById(`scorer-players-list-${team}`);
    if (!container) {
      console.error('Player list container not found:', team);
      return;
    }

    const input = document.createElement('input');
    input.type = 'text';
    input.placeholder = 'Player name';
    input.className = 'form-group';
    input.style.padding = '8px 12px';
    input.style.background = 'rgba(255, 255, 255, 0.05)';
    input.style.border = '1px solid rgba(108, 93, 211, 0.2)';
    input.style.borderRadius = '6px';
    input.style.color = 'white';
    container.appendChild(input);
  } catch (err) {
    console.error('Add scorer player input error:', err);
  }
}

function launchScorecard() {
  try {
    const teamAInput = document.getElementById('score-teamA-name');
    const teamBInput = document.getElementById('score-teamB-name');
    const oversSelect = document.getElementById('score-overs-select');

    const teamA = teamAInput ? teamAInput.value.trim() : '';
    const teamB = teamBInput ? teamBInput.value.trim() : '';
    const overs = oversSelect ? parseInt(oversSelect.value) : 0;
    
    if (!teamA || !teamB) {
      alert('Please enter both team names');
      return;
    }

    if (!validateTeamName(teamA)) {
      alert('Team A name is invalid');
      return;
    }

    if (!validateTeamName(teamB)) {
      alert('Team B name is invalid');
      return;
    }

    if (!validateOvers(overs)) {
      alert('Please select valid overs');
      return;
    }
    
    // Create match object
    const match = {
      id: Date.now(),
      teamA,
      teamB,
      overs,
      date: new Date().toLocaleDateString(),
      innings: [
        {
          team: teamA,
          batsmen: [],
          bowlers: [],
          totalRuns: 0,
          totalWkts: 0,
          legalBalls: 0,
          strikerIdx: 0,
          nonStrikerIdx: 1,
          currentOver: [],
          completedOvers: [],
          extras: {},
          isComplete: false
        }
      ],
      currentInningIdx: 0,
      result: 'In Progress'
    };
    
    // Add players
    const playerInputsA = document.querySelectorAll('#scorer-players-list-A input');
    const playerInputsB = document.querySelectorAll('#scorer-players-list-B input');
    
    playerInputsA.forEach(input => {
      if (input && input.value.trim()) {
        const playerName = input.value.trim();
        if (validatePlayerName(playerName)) {
          match.innings[0].batsmen.push({
            name: playerName,
            runs: 0,
            balls: 0,
            fours: 0,
            sixes: 0,
            dismissed: false,
            dismissal: ''
          });
        }
      }
    });
    
    playerInputsB.forEach(input => {
      if (input && input.value.trim()) {
        const playerName = input.value.trim();
        if (validatePlayerName(playerName)) {
          match.innings[0].bowlers.push({
            name: playerName,
            overs: 0,
            maidens: 0,
            runs: 0,
            wickets: 0
          });
        }
      }
    });
    
    if (match.innings[0].batsmen.length < 2) {
      alert('Please add at least 2 batsmen');
      return;
    }
    
    currentMatch = match;
    currentMatch.currentInning = match.innings[0];
    scoreHistory = [];
    
    // Show active scorer
    const setupEl = document.getElementById('scorer-setup');
    const activeEl = document.getElementById('scorer-active');
    if (setupEl) setupEl.style.display = 'none';
    if (activeEl) activeEl.style.display = 'grid';
    
    // Update UI
    const teamLabel = document.getElementById('score-live-team-label');
    if (teamLabel) teamLabel.textContent = `${teamA} Batting`;
    
    // Populate striker select
    const strikerSelect = document.getElementById('score-striker-select');
    if (strikerSelect) {
      strikerSelect.innerHTML = match.innings[0].batsmen.map(b => `<option value="${b.name}">${b.name}</option>`).join('');
    }
    
    // Populate bowler select
    const bowlerSelect = document.getElementById('score-bowler-select');
    if (bowlerSelect) {
      bowlerSelect.innerHTML = match.innings[0].bowlers.map(b => `<option value="${b.name}">${b.name}</option>`).join('');
    }
    
    updateCreaseDetails();
    updateLiveScore();
    
    // Save match
    const matches = loadMatches();
    if (Array.isArray(matches)) {
      matches.push(cloneMatchForStorage(match));
      saveMatches(matches);
    }

    if (StorageMonitor.shouldWarn()) {
      StorageMonitor.showWarning();
    }
  } catch (err) {
    console.error('Launch scorecard error:', err);
    alert('Failed to launch scorecard. Please try again.');
  }
}

function saveCurrentMatch() {
  try {
    if (!currentMatch || typeof currentMatch.id !== 'number') {
      console.error('Invalid current match:', currentMatch);
      return;
    }

    const matches = loadMatches();
    if (!Array.isArray(matches)) {
      throw new Error('Invalid matches data');
    }

    const idx = matches.findIndex(m => m && m.id === currentMatch.id);
    const matchForStorage = cloneMatchForStorage(currentMatch);
    if (idx !== -1) {
      matches[idx] = matchForStorage;
    } else {
      matches.push(matchForStorage);
    }
    saveMatches(matches);
    
    if (StorageMonitor.shouldWarn()) {
      StorageMonitor.showWarning();
    }
  } catch (err) {
    console.error('Save current match error:', err);
  }
}

function cloneMatchForStorage(match) {
  const matchClone = { ...match };
  delete matchClone.currentInning;
  if (Array.isArray(match.innings)) {
    matchClone.innings = match.innings.map(inning => ({ ...inning }));
  }
  return matchClone;
}

// ============ STORAGE FUNCTIONS - WITH ERROR HANDLING ============
function loadTournaments() {
  try {
    const data = localStorage.getItem(STORAGE_TOURNAMENTS);
    if (!data) return [];
    const parsed = JSON.parse(data);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Load tournaments error:', err);
    return [];
  }
}

function saveTournaments(data) {
  try {
    if (!Array.isArray(data)) {
      throw new Error('Invalid tournaments data format');
    }
    localStorage.setItem(STORAGE_TOURNAMENTS, JSON.stringify(data));
  } catch (err) {
    console.error('Save tournaments error:', err);
    if (err.name === 'QuotaExceededError') {
      alert('Storage quota exceeded. Please remove old tournaments or clean up data.');
    }
  }
}

function loadPlayers() {
  try {
    const data = localStorage.getItem(STORAGE_PLAYERS);
    if (!data) return [];
    const parsed = JSON.parse(data);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Load players error:', err);
    return [];
  }
}

function savePlayers(data) {
  try {
    if (!Array.isArray(data)) {
      throw new Error('Invalid players data format');
    }
    localStorage.setItem(STORAGE_PLAYERS, JSON.stringify(data));
  } catch (err) {
    console.error('Save players error:', err);
    if (err.name === 'QuotaExceededError') {
      alert('Storage quota exceeded. Removing old photos...');
      StorageMonitor.cleanupPhotos();
    }
  }
}

function loadMatches() {
  try {
    const data = localStorage.getItem(STORAGE_MATCHES);
    if (!data) return [];
    const parsed = JSON.parse(data);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    console.error('Load matches error:', err);
    return [];
  }
}

function saveMatches(data) {
  try {
    if (!Array.isArray(data)) {
      throw new Error('Invalid matches data format');
    }
    localStorage.setItem(STORAGE_MATCHES, JSON.stringify(data));
  } catch (err) {
    console.error('Save matches error:', err);
    if (err.name === 'QuotaExceededError') {
      alert('Storage quota exceeded. Please clean up old matches.');
    }
  }
}

function loadAllData() {
  try {
    loadTournaments();
    loadPlayers();
    loadMatches();
  } catch (err) {
    console.error('Load all data error:', err);
  }
}

// ============ TAB NAVIGATION ============
function showTourneySubTab(tab, el) {
  try {
    if (!tab || typeof tab !== 'string' || !el) {
      console.error('Invalid tab parameters');
      return;
    }

    const tabElements = document.querySelectorAll('.tsub-section');
    tabElements.forEach(s => s.style.display = 'none');
    
    const targetTab = document.getElementById(`tsub-${tab}`);
    if (targetTab) {
      targetTab.style.display = 'block';
    }
    
    const innerTabs = el.closest('.inner-tabs');
    if (innerTabs) {
      innerTabs.querySelectorAll('.inner-tab').forEach(t => t.classList.remove('active'));
    }
    el.classList.add('active');
  } catch (err) {
    console.error('Show tourney sub tab error:', err);
  }
}

function showScorecardSubTab(tab, el) {
  try {
    if (!tab || typeof tab !== 'string' || !el) {
      console.error('Invalid tab parameters');
      return;
    }

    const tabElements = document.querySelectorAll('.ssub-section');
    tabElements.forEach(s => s.style.display = 'none');
    
    const targetTab = document.getElementById(`ssub-${tab}`);
    if (targetTab) {
      targetTab.style.display = 'block';
    }
    
    const innerTabs = el.closest('.inner-tabs');
    if (innerTabs) {
      innerTabs.querySelectorAll('.inner-tab').forEach(t => t.classList.remove('active'));
    }
    el.classList.add('active');
  } catch (err) {
    console.error('Show scorecard sub tab error:', err);
  }
}

function showMatchCenterTab(tab, el) {
  try {
    if (!tab || typeof tab !== 'string' || !el) {
      console.error('Invalid tab parameters');
      return;
    }

    const parentCard = el.closest('.glass-card');
    if (!parentCard) {
      console.error('Parent card not found');
      return;
    }

    parentCard.querySelectorAll('.mc-tab-section').forEach(s => s.style.display = 'none');
    
    const targetTab = parentCard.querySelector(`#mc-${tab}`);
    if (targetTab) {
      targetTab.style.display = 'block';
    }
    
    const innerTabs = el.closest('.inner-tabs');
    if (innerTabs) {
      innerTabs.querySelectorAll('.inner-tab').forEach(t => t.classList.remove('active'));
    }
    el.classList.add('active');
  } catch (err) {
    console.error('Show match center tab error:', err);
  }
}

// ============ MODAL HELPERS ============
function openAddTeamModal() {
  try {
    openModal('modal-add-team');
  } catch (err) {
    console.error('Open add team modal error:', err);
  }
}

function openScheduleMatchModal() {
  try {
    if (!currentTournament) {
      alert('Please select a tournament first');
      return;
    }
    
    const select = document.getElementById('schedule-teamA-select');
    const selectB = document.getElementById('schedule-teamB-select');

    if (!select || !selectB) {
      console.error('Schedule match select elements not found');
      return;
    }

    select.innerHTML = (currentTournament.teams || []).map(t => {
      if (!t) return '';
      return `<option value="${t.name}">${t.name}</option>`;
    }).join('');
    
    selectB.innerHTML = (currentTournament.teams || []).map(t => {
      if (!t) return '';
      return `<option value="${t.name}">${t.name}</option>`;
    }).join('');
    
    openModal('modal-schedule-match');
  } catch (err) {
    console.error('Open schedule match modal error:', err);
  }
}

function openAddPlayerModal() {
  try {
    openAddPlayerModalGlobal();
  } catch (err) {
    console.error('Open add player modal error:', err);
  }
}

function loadTournamentMatchOptions() {
  // Placeholder
}

function loadScheduledMatchDetails() {
  // Placeholder
}

function toggleWktFielderField() {
  try {
    const dismissalSelect = document.getElementById('wkt-dismissal-type-select');
    const fielderDiv = document.getElementById('wkt-fielder-div');
    const fielderLabel = document.getElementById('wkt-fielder-label');
    
    if (!dismissalSelect || !fielderDiv || !fielderLabel) {
      console.error('Wicket fielder elements not found');
      return;
    }

    const dismissalType = dismissalSelect.value;
    
    if (['Caught', 'Run Out', 'Stumped'].includes(dismissalType)) {
      fielderDiv.style.display = 'block';
      fielderLabel.textContent = dismissalType === 'Caught' ? 'Caught By' : 'Run Out By';
    } else {
      fielderDiv.style.display = 'none';
    }
  } catch (err) {
    console.error('Toggle wkt fielder field error:', err);
  }
}

function renderProfileStatsFiltered() {
  // Placeholder for tournament filter
}

function renderMatchCenterCommentary() {
  // Placeholder for commentary rendering
}

// Initialize icons on load
window.addEventListener('load', () => {
  try {
    lucide.createIcons();
  } catch (err) {
    console.error('Icon creation error:', err);
  }
});
