import React, { useMemo, useState } from 'react';
import {
  Alert,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import { useVideoPlayer, VideoView } from 'expo-video';
import { StatusBar } from 'expo-status-bar';

const STREAM_DESTINATIONS = {
  youtube: {
    label: 'YouTube Live',
    server: 'rtmps://a.rtmps.youtube.com/live2',
    help: 'Use this with the stream key from YouTube Studio.'
  },
  facebook: {
    label: 'Facebook Live',
    server: 'rtmps://live-api-s.facebook.com:443/rtmp',
    help: 'Use the key generated by Facebook Live Producer.'
  },
  twitch: {
    label: 'Twitch',
    server: 'rtmp://live.twitch.tv/app',
    help: 'Use your Twitch primary stream key.'
  },
  custom: {
    label: 'Custom RTMP',
    server: '',
    help: 'Use the RTMP server supplied by your broadcast provider.'
  }
};

const runButtons = [0, 1, 2, 3, 4, 6];

export default function App() {
  const [teamA, setTeamA] = useState('Team A');
  const [teamB, setTeamB] = useState('Team B');
  const [runs, setRuns] = useState(0);
  const [wickets, setWickets] = useState(0);
  const [balls, setBalls] = useState(0);
  const [streamUrl, setStreamUrl] = useState('');
  const [platform, setPlatform] = useState('youtube');
  const [streamKey, setStreamKey] = useState('');

  const overs = `${Math.floor(balls / 6)}.${balls % 6}`;
  const runRate = balls > 0 ? (runs / (balls / 6)).toFixed(2) : '0.00';
  const destination = STREAM_DESTINATIONS[platform];
  const serverUrl = platform === 'custom' ? streamUrl : destination.server;
  const canPreviewVideo = /^https?:\/\//i.test(streamUrl);
  const player = useVideoPlayer(canPreviewVideo ? streamUrl : null, (videoPlayer) => {
    videoPlayer.loop = false;
  });

  const scoreText = useMemo(() => `${runs}/${wickets} (${overs})`, [runs, wickets, overs]);

  const scoreRun = (value) => {
    setRuns((current) => current + value);
    setBalls((current) => current + 1);
  };

  const addWicket = () => {
    if (wickets >= 10) {
      Alert.alert('Innings complete', 'All 10 wickets are already down.');
      return;
    }
    setWickets((current) => current + 1);
    setBalls((current) => current + 1);
  };

  const resetScore = () => {
    setRuns(0);
    setWickets(0);
    setBalls(0);
  };

  const showTelecastInfo = () => {
    Alert.alert(
      'Telecast Info',
      [
        `Platform: ${destination.label}`,
        `Server URL: ${serverUrl || '[enter custom RTMP server]'}`,
        `Stream Key: ${streamKey || '[paste stream key]'}`,
        `Score Overlay: ${scoreText}`,
      ].join('\n')
    );
  };

  return (
    <SafeAreaView style={styles.screen}>
      <StatusBar style="light" />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <Text style={styles.kicker}>Cricket Management Pro</Text>
          <Text style={styles.title}>Live Score & Stream</Text>
        </View>

        <View style={styles.videoFrame}>
          {canPreviewVideo ? (
            <VideoView
              player={player}
              style={StyleSheet.absoluteFill}
              allowsFullscreen
              allowsPictureInPicture
              nativeControls
              contentFit="contain"
            />
          ) : (
            <View style={styles.videoPlaceholder}>
              <Text style={styles.placeholderTitle}>Broadcast Preview</Text>
              <Text style={styles.placeholderText}>Paste an HLS or MP4 URL to preview video.</Text>
            </View>
          )}

          <View style={styles.overlay}>
            <Text style={styles.overlayTeam} numberOfLines={1}>{teamA} batting vs {teamB}</Text>
            <Text style={styles.overlayScore}>{scoreText}</Text>
            <Text style={styles.overlayMeta}>RR {runRate}</Text>
          </View>
        </View>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Teams</Text>
          <TextInput style={styles.input} value={teamA} onChangeText={setTeamA} placeholder="Batting team" />
          <TextInput style={styles.input} value={teamB} onChangeText={setTeamB} placeholder="Bowling team" />
        </View>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Score Controls</Text>
          <View style={styles.runGrid}>
            {runButtons.map((value) => (
              <TouchableOpacity key={value} style={styles.runButton} onPress={() => scoreRun(value)}>
                <Text style={styles.runButtonText}>{value}</Text>
              </TouchableOpacity>
            ))}
          </View>
          <View style={styles.row}>
            <TouchableOpacity style={styles.secondaryButton} onPress={addWicket}>
              <Text style={styles.secondaryButtonText}>Wicket</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.secondaryButton} onPress={resetScore}>
              <Text style={styles.secondaryButtonText}>Reset</Text>
            </TouchableOpacity>
          </View>
        </View>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Stream Preview</Text>
          <TextInput
            style={styles.input}
            value={streamUrl}
            onChangeText={setStreamUrl}
            placeholder="HLS/MP4 preview URL or custom RTMP server"
            autoCapitalize="none"
          />
        </View>

        <View style={styles.panel}>
          <Text style={styles.panelTitle}>Telecast Destination</Text>
          <View style={styles.platformGrid}>
            {Object.keys(STREAM_DESTINATIONS).map((key) => (
              <TouchableOpacity
                key={key}
                style={[styles.platformButton, platform === key && styles.platformButtonActive]}
                onPress={() => setPlatform(key)}
              >
                <Text style={[styles.platformText, platform === key && styles.platformTextActive]}>
                  {STREAM_DESTINATIONS[key].label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
          <TextInput
            style={styles.input}
            value={streamKey}
            onChangeText={setStreamKey}
            placeholder="Stream key / stream name"
            autoCapitalize="none"
          />
          <View style={styles.destinationBox}>
            <Text style={styles.destinationLabel}>Server URL</Text>
            <Text style={styles.destinationText}>{serverUrl || 'Enter a custom RTMP server above'}</Text>
            <Text style={styles.destinationHelp}>{destination.help}</Text>
          </View>
          <TouchableOpacity style={styles.primaryButton} onPress={showTelecastInfo}>
            <Text style={styles.primaryButtonText}>Show Telecast Info</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#09111f',
  },
  content: {
    padding: 16,
    gap: 14,
  },
  header: {
    paddingVertical: 10,
  },
  kicker: {
    color: '#7dd3fc',
    fontSize: 13,
    fontWeight: '700',
  },
  title: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    marginTop: 4,
  },
  videoFrame: {
    aspectRatio: 16 / 9,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#243244',
  },
  videoPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  placeholderTitle: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
  },
  placeholderText: {
    color: '#9ca3af',
    marginTop: 6,
    textAlign: 'center',
  },
  overlay: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(2, 6, 23, 0.82)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  overlayTeam: {
    flex: 1,
    color: '#e5e7eb',
    fontSize: 12,
    fontWeight: '700',
  },
  overlayScore: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: '900',
  },
  overlayMeta: {
    color: '#fbbf24',
    fontSize: 12,
    fontWeight: '800',
  },
  panel: {
    gap: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#243244',
  },
  panelTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  input: {
    minHeight: 44,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    color: '#0f172a',
  },
  runGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  runButton: {
    width: 52,
    height: 52,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563eb',
  },
  runButtonText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#334155',
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  platformGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  platformButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#374151',
  },
  platformButtonActive: {
    backgroundColor: '#0ea5e9',
    borderColor: '#38bdf8',
  },
  platformText: {
    color: '#d1d5db',
    fontWeight: '700',
    fontSize: 12,
  },
  platformTextActive: {
    color: '#ffffff',
  },
  destinationBox: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: '#334155',
  },
  destinationLabel: {
    color: '#93c5fd',
    fontWeight: '800',
    fontSize: 12,
  },
  destinationText: {
    color: '#ffffff',
    marginTop: 4,
  },
  destinationHelp: {
    color: '#9ca3af',
    marginTop: 6,
    fontSize: 12,
  },
  primaryButton: {
    minHeight: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f59e0b',
  },
  primaryButtonText: {
    color: '#111827',
    fontWeight: '900',
  },
});
